"""
SQL Executor
============

Purpose:
    This module is responsible for reading SQL files from the
    project's sql/ directory and executing them in Snowflake.

Architecture:

    SQL files
        |
        v
    sql_executor.py
        |
        v
    Snowflake

Responsibilities:

    SQL files:
        - Database setup
        - Table creation
        - Data loading
        - Data quality checks
        - Analytics
        - Pipeline audit

    Python:
        - Read SQL files
        - Execute SQL
        - Handle errors
        - Control pipeline execution
"""


# ============================================================
# IMPORTS
# ============================================================

from io import StringIO

from python.config import SQL_DIR


# ============================================================
# READ SQL FILE
# ============================================================

def read_sql_file(file_name: str) -> str:
    """
    Read a SQL file from the project's sql directory.

    Parameters
    ----------
    file_name : str
        Name of the SQL file.

    Returns
    -------
    str
        Complete SQL content.

    Raises
    ------
    FileNotFoundError
        If the SQL file does not exist.
    """

    # --------------------------------------------------------
    # Build the complete path to the SQL file.
    # --------------------------------------------------------

    sql_file = SQL_DIR / file_name


    # --------------------------------------------------------
    # Check that the file exists.
    # --------------------------------------------------------

    if not sql_file.exists():

        raise FileNotFoundError(
            f"SQL file not found: {sql_file}"
        )


    # --------------------------------------------------------
    # Make sure the path is actually a file.
    # --------------------------------------------------------

    if not sql_file.is_file():

        raise FileNotFoundError(
            f"SQL path is not a file: {sql_file}"
        )


    # --------------------------------------------------------
    # Read the SQL file using UTF-8 encoding.
    # --------------------------------------------------------

    sql_content = sql_file.read_text(
        encoding="utf-8"
    )


    return sql_content


# ============================================================
# EXECUTE SINGLE SQL STATEMENT
# ============================================================

def execute_sql(connection, sql: str):
    """
    Execute one SQL statement in Snowflake.

    Parameters
    ----------
    connection
        Active Snowflake connection.

    sql : str
        SQL statement to execute.

    Returns
    -------
    cursor
        Snowflake cursor.
    """

    # --------------------------------------------------------
    # Create a cursor.
    # --------------------------------------------------------

    cursor = connection.cursor()


    try:

        # ----------------------------------------------------
        # Execute the SQL statement.
        # ----------------------------------------------------

        cursor.execute(sql)


        # ----------------------------------------------------
        # Return the cursor so the caller can inspect the
        # result.
        # ----------------------------------------------------

        return cursor


    except Exception:

        # ----------------------------------------------------
        # Close the cursor if execution fails.
        # ----------------------------------------------------

        cursor.close()

        raise


# ============================================================
# EXECUTE COMPLETE SQL FILE
# ============================================================

def execute_sql_file(connection, file_name: str):
    """
    Execute all SQL statements contained in a SQL file.

    Parameters
    ----------
    connection
        Active Snowflake connection.

    file_name : str
        Name of the SQL file inside the sql directory.

    Returns
    -------
    list
        List of Snowflake cursors generated by the SQL script.

    Notes
    -----
    Snowflake's execute_stream() expects a file-like object.

    Therefore, the SQL string is wrapped in StringIO.

    StringIO behaves like a normal file and provides methods
    such as readline(), which execute_stream() expects.
    """

    # --------------------------------------------------------
    # Read the SQL file.
    # --------------------------------------------------------

    sql_content = read_sql_file(
        file_name
    )


    # --------------------------------------------------------
    # Prevent execution of an empty SQL file.
    # --------------------------------------------------------

    if not sql_content.strip():

        raise ValueError(
            f"SQL file is empty: {file_name}"
        )


    # --------------------------------------------------------
    # Create a file-like object from the SQL string.
    #
    # This is the important fix.
    #
    # Instead of:
    #
    #     execute_stream(sql_content)
    #
    # we use:
    #
    #     execute_stream(StringIO(sql_content))
    #
    # --------------------------------------------------------

    sql_stream = StringIO(
        sql_content
    )


    # --------------------------------------------------------
    # Store all cursors returned by Snowflake.
    # --------------------------------------------------------

    cursors = []


    try:

        # ----------------------------------------------------
        # Execute the SQL script.
        # ----------------------------------------------------

        for cursor in connection.execute_stream(
            sql_stream
        ):

            cursors.append(cursor)


        # ----------------------------------------------------
        # Return the generated cursors.
        # ----------------------------------------------------

        return cursors


    except Exception:

        # ----------------------------------------------------
        # If execution fails, close cursors that were already
        # created.
        # ----------------------------------------------------

        for cursor in cursors:

            try:

                cursor.close()

            except Exception:

                pass


        raise


    finally:

        # ----------------------------------------------------
        # Close the in-memory SQL file.
        # ----------------------------------------------------

        sql_stream.close()